# **Import All Libraries using in this project**

In [3]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline

Using TensorFlow backend.


In [4]:
seed = 7
np.random.seed(seed)


# **Upload csv file using pandas from local computer storage and show the data**

In [8]:
import io
df = pd.read_csv(('iris.csv') , header = None)
df

FileNotFoundError: File b'iris.csv' does not exist

# **Convert the data into numpy and print 1st row , dimensions , shape and type of data**

In [0]:
dataset = df.values
print(dataset[0])
print(dataset.ndim)
print(dataset.shape)
print(type(dataset))

[5.1 3.5 1.4 0.2 'Iris-setosa']
2
(150, 5)
<class 'numpy.ndarray'>


# **Split and print samples and labes and their shapes**

In [0]:
x = dataset[:,0:4].astype(float)
y = dataset[:,4]
print(x[0])
print(y)
print(x.shape)
print(y.shape)

[5.1 3.5 1.4 0.2]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

# **Encode the string labels into binary digits 0 for Mines and 1 for Rock using sciket learn LabelEncoder()**

In [0]:
encoder = LabelEncoder()
encoder.fit(y)
encoded_y = encoder.transform(y)
dummy_y = np_utils.to_categorical(encoded_y)
dummy_y[0:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

# **Create a baseline model using Sequential**

In [0]:
from keras import optimizers
def baseline_model():
  baseline_network = Sequential()
  baseline_network.add(Dense(8, activation='relu', input_shape=(4,)))
  baseline_network.add(Dense(3, activation='softmax'))
  baseline_network.compile(optimizer= optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-8), loss='categorical_crossentropy' , metrics=["accuracy"])
  return baseline_network
  

# **Run the model**

In [0]:
estimator = KerasClassifier(build_fn = baseline_model , epochs = 200 , batch_size = 5 , verbose = 0 )
kfold = KFold(n_splits = 10 , shuffle = True , random_state = seed)
results = cross_val_score(estimator , x , dummy_y , cv = kfold)
print("Accuracy: %2f%%(%2f%%)"%(results.mean()*100,results.std()*100))

Accuracy: 97.333333%(4.422166%)


# **Now tuning the layes and build smaller network**

In [0]:
from keras import optimizers
def small_model():
  small_network = Sequential()
  small_network.add(Dense(6, activation='relu', input_shape=(4,)))
  small_network.add(Dense(3, activation='softmax'))
  small_network.compile(optimizer= optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-8), loss='categorical_crossentropy' , metrics=["accuracy"])
  return small_network
  

# **Run the model**

In [0]:
estimator = KerasClassifier(build_fn = small_model , epochs = 100 , batch_size = 5 , verbose = 0 )
kfold = KFold(n_splits = 10 , shuffle = True , random_state = seed)
results = cross_val_score(estimator , x , dummy_y , cv = kfold)
print("Small_Accuracy: %2f%%(%2f%%)"%(results.mean()*100,results.std()*100))

Small_Accuracy: 95.333334%(5.206833%)


# **Now add two more layer and create larger network**

In [0]:
from keras import optimizers
def large_model():
  large_network = Sequential()
  large_network.add(Dense(8, activation='relu', input_shape=(4,)))
  large_network.add(Dense(8, activation='relu'))
  large_network.add(Dense(4, activation='relu'))
  large_network.add(Dense(3, activation='softmax'))
  large_network.compile(optimizer= optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-8), loss='categorical_crossentropy' , metrics=["accuracy"])
  return large_network
  

# **Now run the model**

In [0]:
estimator = KerasClassifier(build_fn = large_model , epochs = 200 , batch_size = 5 , verbose = 0 )
kfold = KFold(n_splits = 10 , shuffle = True , random_state = seed)
results = cross_val_score(estimator , x , dummy_y , cv = kfold)
print("Large_Accuracy: %2f%%(%2f%%)"%(results.mean()*100,results.std()*100))

Large_Accuracy: 84.666667%(24.413111%)


# **Build Model that overfit**

In [0]:
from keras import optimizers
def overfit_model():
  network = Sequential()
  network.add(Dense(12, activation='relu', input_shape=(4,)))
  network.add(Dense(10, activation='relu'))
  network.add(Dense(8, activation='relu'))
  network.add(Dense(3, activation='softmax'))
  network.compile(optimizer= optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-8), loss='categorical_crossentropy' , metrics=["accuracy"])
  return network
  

# **Run As always**

In [0]:
estimator = KerasClassifier(build_fn = overfit_model , epochs = 300, batch_size = 5 , verbose = 0 )
kfold = KFold(n_splits = 10 , shuffle = True , random_state =
 seed)
results = cross_val_score(estimator , x , dummy_y , cv = kfold)
print("Accuracy: %2f%%(%2f%%)"%(results.mean()*100,results.std()*100))

# **Build model with functional API**

In [0]:
from keras.layers import Input, Dense
from keras.models import Model
def functional_model():
  inputs = Input(shape = (4,))
  z = Dense(8, activation='relu')(inputs)
  outputs = Dense(3 , activation = 'softmax')(z)
  model = Model(inputs,outputs)
  model.compile(optimizer= optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-8), loss='categorical_crossentropy', metrics=['acc'])
  return model

# **Run the Model**

In [0]:
estimator = KerasClassifier(build_fn = functional_model  , epochs = 200, batch_size = 5 , verbose = 0 )
kfold = KFold(n_splits = 10 , shuffle = True , random_state = seed)
results = cross_val_score(estimator , x , dummy_y , cv = kfold)
print("Accuracy: %2f%%(%2f%%)"%(results.mean()*100,results.std()*100))

Accuracy: 95.333334%(4.268749%)


# **Build Model with Model subclassing**

In [1]:
import tensorflow as tf
class SubclassModel(tf.keras.Model):
    def __init__(self):
        super(SubclassModel,self).__init__()
        self.dense1= tf.keras.layers.Dense(8,activation=tf.nn.relu)
        self.dense2=tf.keras.layers.Dense(6,activation=tf.nn.relu)
        self.dense3= tf.keras.layers.Dense(3,activation=tf.nn.softmax)
    def call(self,inputs):
        x=self.dense1(inputs)
        x=self.dense2(x)
        return self.dense3(x)
def finalModel():
    model=SubclassModel()
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model




# **Runnn**

In [2]:
estimator = KerasClassifier(build_fn = finalModel  , epochs = 200, batch_size = 5 , verbose = 0 )
kfold = KFold(n_splits = 10 , shuffle = True , random_state = seed)
results = cross_val_score(estimator , x , dummy_y , cv = kfold)
print("Accuracy: %2f%%(%2f%%)"%(results.mean()*100,results.std()*100))

NameError: name 'KerasClassifier' is not defined

# **Build Model from scratch without Scikit Learn**

In [0]:
complete_data = dataset.copy()
np.random.shuffle(complete_data)
data = complete_data[:,0:4].astype('float32')
labels = complete_data[:,4]
le = LabelEncoder()
le.fit(labels)
encode_labels = le.transform(labels).astype('float32')
hot_encode_labels = np_utils.to_categorical(encode_labels)
print(hot_encode_labels)
print(data.dtype)
train_dataset = data[:100]
test_dataset = data[100:]
train_label = hot_encode_labels[:100]
test_label = hot_encode_labels[100:]
print(train_label.shape)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0.

In [0]:
def build_final_model():
  network = Sequential()
  network.add(Dense(4, activation='relu', input_shape=(4,)))
  network.add(Dense(3, activation='softmax'))
  network.compile(optimizer= optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-8), loss='categorical_crossentropy' , metrics=["accuracy"])
  return network
  

In [0]:
k=4
num_val_samples = len(train_dataset) // k
num_epochs = 200

for i in range(k):
  print('processing fold #', i)
  val_data = train_dataset[i * num_val_samples: (i + 1) * num_val_samples]
  val_labels = train_label[i * num_val_samples: (i + 1) * num_val_samples]
  partial_train_data = np.concatenate(
      [train_dataset[:i * num_val_samples],train_dataset[(i + 1) * num_val_samples:]],axis=0)
  partial_train_labels = np.concatenate(
      [train_label[:i * num_val_samples],
       train_label[(i + 1) * num_val_samples:]])
  model = build_final_model()
  model.fit(partial_train_data, partial_train_labels , validation_data=(val_data, val_labels), epochs=num_epochs, batch_size=1, verbose=0)
  loss , acc = model.evaluate(val_data, val_labels , verbose=0)
  print(acc)
  
  

processing fold # 0
0.3199999928474426
processing fold # 1
0.2800000011920929
processing fold # 2
1.0
processing fold # 3
0.9599999785423279


In [0]:
def final_model():
  network = Sequential()
  network.add(Dense(4, activation='relu', input_shape=(4,)))
  network.add(Dense(3, activation='softmax'))
  network.compile(optimizer= optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-8), loss='categorical_crossentropy' , metrics=["accuracy"])
  return network

model = final_model()
model.fit(train_dataset, train_label , epochs=100, batch_size=5 , verbose=1)

Epoch 1/100
100/100 [==============================] - 3s 28ms/step - loss: 1.4409 - acc: 0.2900
Epoch 2/100
100/100 [==============================] - 0s 695us/step - loss: 1.3117 - acc: 0.2900
Epoch 3/100
100/100 [==============================] - 0s 686us/step - loss: 1.2140 - acc: 0.2900
Epoch 4/100
100/100 [==============================] - 0s 755us/step - loss: 1.1287 - acc: 0.2900
Epoch 5/100
100/100 [==============================] - 0s 717us/step - loss: 1.0637 - acc: 0.3200
Epoch 6/100
100/100 [==============================] - 0s 608us/step - loss: 1.0102 - acc: 0.4300
Epoch 7/100
100/100 [==============================] - 0s 656us/step - loss: 0.9710 - acc: 0.5100
Epoch 8/100
100/100 [==============================] - 0s 652us/step - loss: 0.9448 - acc: 0.5400
Epoch 9/100
100/100 [==============================] - 0s 706us/step - loss: 0.9245 - acc: 0.5400
Epoch 10/100
100/100 [==============================] - 0s 530us/step - loss: 0.9090 - acc: 0.4500
Epoch 11/100
100/100

In [0]:
history = model.evaluate(test_dataset, test_label)
history

50/50 [==============================] - 1s 22ms/step


[0.3473368775844574, 0.94]